### PR TITLE
Support process SOAP 1.2 reply

### PR DESCRIPTION
**Pull request by eshizhan**

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks for the contribution. Can you please add a test covering this
behavior?

**Comment by eshizhan** [comment]
@phillbaker add test case, thx for review!

**Comment by phillbaker** [comment]
Hi, it looks like the test suite is failing on CI. Can you take a look at
the failing tests?

**Comment by eshizhan** [comment]
I saw it, but these failures have nothing to do with this PR. I think these failures seem to be related to pytest in the CI environment. Some failed methods are marked `@pytest.mark.xfail`.

**Comment by eshizhan** [comment]
The reason is `3.x` bump to 3.12, it's remove `distutils` module.

**Comment by phillbaker** [comment]
Thanks, I’ll check it out.

**Comment by phillbaker** [comment]
Sorry for the slow update here, fixes have been merged to master to fix python 3.12, can you rebase your branch please?

**Pull request merged**
