### PR TITLE
Add CI testing for Python 3.7 and 3.8 (dev)

### PR DESCRIPTION
**Pull request by swt2c**

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks! Looks like Travis didn’t like this though. Is the distro argument
needed?

**Comment by swt2c** [comment]
Yeah, it is needed for 3.7+.  I'll try going back to xenial.

**Comment by swt2c** [comment]
That fixed things, but it seems more fixes are needed for 3.8.

**Comment by swt2c** [comment]
Should be good now.

**Pull request merged**
