### PR TITLE
Instantiate without empty optional

### PR DESCRIPTION
**Pull request by guifran001**
I think this simple change fixes everything without breaking what the fix was originally made for

### CODE REVIEW

**Comment by phillbaker** [comment]
Awesome, will review shortly.

**Comment by phillbaker** [comment]
Thanks, will bump and get a new version out soon

**Comment by guifran001** [comment]
@phillbaker : Thank you.  When do you think you can release it? My team is looking forward to give it a try

**Comment by phillbaker** [comment]
Should be released now. Thanks!

**Pull request merged**
